# Non-terminal Expansions

<root> ::= "<?xml version=\"1.0\" ?>" \n "<rulebase>"\n<initialize><ruleset>"</rulebase>"\n
<initialize> ::= "<initial_state " p1=\"<prob_init_state> \" " " p2=\"<prob_init_state> \" " " p3=\"<prob_init_state> \" "/>"\n
<ruleset> ::= <rule><ruleset>|<rule>
<rule> ::= "<rule>"\n<firstpart><secondpart><thirdpart>"</rule>"\n
<firstpart> ::= "<previous_states>"\n<ps_list>"</previous_states>"\n
<secondpart> ::= "<preconditions>"\n<pc_list>"</preconditions>"\n
<thirdpart> ::= "<actions>"\n<a_list>"</actions>"\n

# List of previous states.
<ps_list> ::= <ps>|<ps><ps>|<ps><ps><ps>
<ps> ::= "<prv_state " id=\"<id_state>\" "/>"\n

# List of previous preconditions.
<pc_list> ::= <pc>|<pc><pc>|<pc><pc><pc>|<pc><pc><pc><pc>
<pc> ::= "<precond " id=\"<id_precondition>\" " " value=<bool>"/>"\n

# List of actions.
<a_list> ::= <action>|<action><action>|<action><action><action>|<action><action><action><action>
<action> ::= <action_cngstate>|<action_cngvar>
<action_cngstate> ::= "<act " type=\"1\" " " prob=\"<probability>\" " " nxt_state_id=\"<id_state>\""/>"\n
<action_cngvar> ::= "<act " type=\"2\" " " prob=\"<probability>\" " " variable_id=\"<id_var>\" " " value=<bool>"/>"\n



# Terminal Expansions.

<id_state>::=0|1|2
<id_precondition>::=0|1|2|3|5|7|8
<id_var>::=1|2|3|4
<probability>::=0.001|0.005|0.01|0.025|0.05|0.075|0.1|1.0
<bool>::=\"true\"|\"false\"
<prob_init_state>::=0.0|0.1|0.2|0.3|0.4|0.5|0.6|0.7|0.8|0.9|1.0
