# Non-terminal Expansions

<root> ::= <statoiniziale><ruleset>
<statoiniziale> ::= <prob_init_state><prob_init_state><prob_init_state>
<ruleset> ::= <rule><ruleset>|<rule>
<rule> ::= <firstpart><secondpart><thirdpart>
<firstpart> ::= <ps_list>
<secondpart> ::= <pc_list>
<thirdpart> ::= <a_list>

# List of previous states.
<ps_list> ::= <ps>|<ps><ps>|<ps><ps><ps>
<ps> ::= <id_state>

# List of previous preconditions.
<pc_list> ::= <pc>|<pc><pc>|<pc><pc><pc>|<pc><pc><pc><pc>
<pc> ::= <id_precondition><bool>

# List of actions.
<a_list> ::= <action>|<action><action>|<action><action><action>|<action><action><action><action>
<action> ::= <action_cngstate>|<action_cngvar>
<action_cngstate> ::= <probability><id_state>
<action_cngvar> ::= <probability><id_var><bool>



# Terminal Expansions.

<id_state>::=0|1|2
<id_precondition>::=0|1|2|3|5|7|8
<id_var>::=1|2|3|4
<probability>::=0.001|0.005|0.01|0.025|0.05|0.075|0.1|1.0
<bool>::=\"true\"|\"false\"
<prob_init_state>::=0.0|0.1|0.2|0.3|0.4|0.5|0.6|0.7|0.8|0.9|1.0