# automatically generated by the FlatBuffers compiler, do not modify

# namespace: foraging

class IdPrecondition(object):
    PRECONDITION_0 = 0
    PRECONDITION_1 = 1
    PRECONDITION_2 = 2
    PRECONDITION_3 = 3

