# automatically generated by the FlatBuffers compiler, do not modify

# namespace: foraging

import flatbuffers

class Precondition(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsPrecondition(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Precondition()
        x.Init(buf, n + offset)
        return x

    # Precondition
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Precondition
    def IdPrecondition(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

def PreconditionStart(builder): builder.StartObject(1)
def PreconditionAddIdPrecondition(builder, idPrecondition): builder.PrependInt8Slot(0, idPrecondition, 0)
def PreconditionEnd(builder): return builder.EndObject()
