# automatically generated by the FlatBuffers compiler, do not modify

# namespace: foraging

class Probability(object):
    PROB_0 = 0
    PROB_1 = 1
    PROB_2 = 2
    PROB_3 = 3
    PROB_4 = 4
    PROB_5 = 5
    PROB_6 = 6
    PROB_7 = 7

