# automatically generated by the FlatBuffers compiler, do not modify

# namespace: foraging

class ProbInitState(object):
    PROB_INIT_STATE_0 = 0
    PROB_INIT_STATE_1 = 1
    PROB_INIT_STATE_2 = 2
    PROB_INIT_STATE_3 = 3
    PROB_INIT_STATE_4 = 4
    PROB_INIT_STATE_5 = 5
    PROB_INIT_STATE_6 = 6
    PROB_INIT_STATE_7 = 7
    PROB_INIT_STATE_8 = 8
    PROB_INIT_STATE_9 = 9

